import type { Metadata } from "next"
import { Geist } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' >
      <body className={`${geistSans.className} antialiased pt-[60px] px-[100px] not-md:px-[15px] not-md:pt-0`} >{children}</body>
    </html>
  )
}
