import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { GlobalHeader } from "@/components/layout/header/global-header";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} antialiased pt-[60px] px-[100px] not-md:px-[15px] not-md:pt-0`}
      >
        <GlobalHeader></GlobalHeader>
        {children}
      </body>
    </html>
  );
}
